# Generated by Django 2.1.4 on 2018-12-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumlist', '0003_auto_20181204_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=160, unique=True),
        ),
    ]
