# Generated by Django 2.1.4 on 2018-12-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumlist', '0006_remove_album_discogs_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='discogs_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
